import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../style/globals.css";
import { MyNavbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Eventify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`antialiased`}>
        <MyNavbar />
        <div className="container mx-auto px-10 py-5">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
